// import axios from 'axios';
// import React, { useEffect, useState } from 'react';
// import './Header.css'; // Assuming you'll add CSS here

// function Header() {
//   const [userName, setUserName] = useState(''); 
//   const [isLoading, setIsLoading] = useState(true);
//   const [isModalOpen, setIsModalOpen] = useState(false); // State for modal visibility

//   // Fetch user details on component mount
//   useEffect(() => {
//     const fetchUserDetails = async () => {
//       const token = localStorage.getItem('authToken');
//       if (token) {
//         try {
//           const response = await axios.get('https://zencia-finalbackend.vercel.app/api/user', {
//             headers: {
//               'Authorization': `${token}`,
//             },
//           });
//           const { firstName } = response.data.data;
//           setUserName(firstName);
//         } catch (error) {
//           console.error('Error fetching user details:', error);
//           setUserName('User');
//         } finally {
//           setIsLoading(false);
//         }
//       } else {
//         setIsLoading(false);
//       }
//     };

//     fetchUserDetails();
//   }, []);

//   // Toggle modal visibility
//   const toggleModal = () => {
//     setIsModalOpen(!isModalOpen);
//   };

//   return (
//     <>
//       <div className="header">
//         <div className="welcome-text">
//           <h1>
//             {isLoading ? 'Loading...' : `Welcome, ${userName || 'User'}!`}
//           </h1>
//           <p>Manage your Zencia Account</p>
//         </div>
//         <div className="header-actions">
//           <button className="btn btn-primary" onClick={toggleModal}>
//             <span>Get Started</span>
//             <span>→</span>
//           </button>
//         </div>
//       </div>

//       {/* Modal */}
//       {isModalOpen && (
//         <div className="modal-overlay">
//           <div className="modal-content">
        


//           <div style={{ marginBottom: '20px' }}>
//         <h3 style={{ color: '#e0e0e0', marginBottom: '10px', fontWeight: 'bold' }}>Step 1: Download Software</h3>
//         <ul style={{ textAlign: 'left', paddingLeft: '20px', color: '#333' }}>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Go to Zencia.AI website
//           </li>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Find the Downloads section on the homepage
//           </li>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Choose your operating system version
//           </li>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Download the installation file corresponding to your OS
//           </li>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Run the installer and follow the on-screen instructions
//           </li>
//         </ul>
//       </div>

//       <div>
//         <h3 style={{ color: '#e0e0e0', marginBottom: '10px', fontWeight: 'bold' }}>Step 2: Get Hardware ID</h3>
//         <ul style={{ textAlign: 'left', paddingLeft: '20px', color: '#333' }}>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Open the Zencia.AI application
//           </li>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Navigate to the License Management section in the app
//           </li>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Click the 'Generate Key' button
//           </li>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Copy your unique Hardware ID generated by the app
//           </li>
//           <li style={{ color: '#e0e0e0', marginBottom: '10px' }}>
//             Use the Hardware ID for registration and activation
//           </li>
//         </ul>
//       </div>

//             <button className="btn btn-primary" onClick={toggleModal}>
//               Close
//             </button>
//           </div>
//         </div>
//       )}
//     </>
//   );
// }

// export default Header;





import axios from 'axios';
import React, { useEffect, useState } from 'react';
import './Header.css';

function Header() {
  const [userName, setUserName] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);

  // Fetch user details on component mount
  useEffect(() => {
    const fetchUserDetails = async () => {
      const token = localStorage.getItem('authToken');
      if (token) {
        try {
          const response = await axios.get('https://zencia-finalbackend.vercel.app/api/user', {
            headers: {
              'Authorization': `${token}`,
            },
          });
          const { firstName } = response.data.data;
          setUserName(firstName);
        } catch (error) {
          console.error('Error fetching user details:', error);
          setUserName('User');
        } finally {
          setIsLoading(false);
        }
      } else {
        setIsLoading(false);
      }
    };

    fetchUserDetails();
  }, []);

  // Toggle modal visibility
  const toggleModal = () => {
    setIsModalOpen(!isModalOpen);
  };

  return (
    <>
      <div className="header">
        <div className="user-welcome">
          <h1>
            {isLoading ? 'Loading...' : `Welcome, ${userName || 'User'}!`}
          </h1>
          <p>Manage your Zencia Account</p>
        </div>
        <div className="header-actions">
          <button className="btn-get-started" onClick={toggleModal}>
            <span>Get Started</span>
            <span className="arrow">→</span>
          </button>
        </div>
      </div>

      {isModalOpen && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-section">
              <h3>Step 1: Download Software</h3>
              <ul>
                <li>Go to Zencia.AI website</li>
                <li>Find the Downloads section on the Sidebar</li>
                <li>Choose your operating system version</li>
                <li>Download the installation file corresponding to your OS</li>
                <li>Run the installer and follow the on-screen instructions</li>
              </ul>
            </div>

            <div className="modal-section">
              <h3>Step 2: Get Hardware ID</h3>
              <ul>
                <li>After installation, copy the Hardware ID.</li>
                <li>Return to the Dashboard and navigate to Plan Section</li>
                <li>Select the plan, Enter the Hardware ID for which you want to generate a license</li>
                <li>For trial It will Generate License, and For Premium Plan Proceed to Checkout </li>
                <li>Completing the Payment you will get your License Key. Copy the License Key and back to Application and Paste it.</li>
              </ul>
            </div>

            <button className="btn-close" onClick={toggleModal}>
              Close
            </button>
          </div>
        </div>
      )}
    </>
  );
}

export default Header;